// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCahaozufLSX30u89veY1A_zxJdMF9PG-A',
    appId: '1:956533274367:android:441b9fb0f90a3ea5b53eca',
    messagingSenderId: '956533274367',
    projectId: 'qoutemotivation',
    databaseURL: 'https://qoutemotivation-default-rtdb.firebaseio.com',
    storageBucket: 'qoutemotivation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV7AfeVM1XkCFljfBMHSJ-hGgeQxWwwWs',
    appId: '1:956533274367:ios:910ec95b4714ce59b53eca',
    messagingSenderId: '956533274367',
    projectId: 'qoutemotivation',
    databaseURL: 'https://qoutemotivation-default-rtdb.firebaseio.com',
    storageBucket: 'qoutemotivation.appspot.com',
    iosClientId: '956533274367-7ovmj43ncts8ob3g7orau3ulm9avn4ff.apps.googleusercontent.com',
    iosBundleId: 'com.book.axeninfotech',
  );
}
